language: r
cache: packages

sudo: false

repos:
  cran: http://cran.rstudio.com
  rforge: http://R-Forge.R-project.org

r_github_packages:
 - hrbrmstr/statebins
 - cttobin/ggthemr
 - tidyverse/forcats
 - cran/extracat

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev

# safelist
branches:
  only:
  - master

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'


deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github-token: $GITHUB_PAT    # Set in the settings page
  on:
    branch: master
